export * from "./adapters/Product.ApiAdapter";
export { default as Details } from "./components/Details.Product.vue";
export { default as Form } from "./components/Form.Product.vue";
export { default as List } from "./components/List.Product.vue";
export * from "./constans/Product.DefaultFormValue";
export * from "./constans/Product.RoutesDictionary";
export * from "./constans/Product.TableHeader";
export * from "./models/Product";
export * from "./router/Router.Product";
export * from "./schemas/Product.Schema";
export * from "./services/Product.ApiPetitions";
