export * from './adapters/Client.ApiAdapter';
export { default as Details } from './components/Details.Client.vue';
export { default as Form } from './components/Form.Client.vue';
export { default as List } from './components/List.Client.vue';
export { default as AdressesForm } from './components/client-data/addresses/AdressesForm.vue';
export { default as AdressesList } from './components/client-data/addresses/AdressesList.vue';
export { default as EmailsForm } from './components/client-data/emails/EmailsForm.vue';
export { default as EmailsList } from './components/client-data/emails/EmailsList.vue';
export { default as PhonesForm } from './components/client-data/phones/PhonesForm.vue';
export { default as PhonesList } from './components/client-data/phones/PhonesList.vue';
export * from './constants/Client.DefaultFormValue';
export * from './constants/Client.FormatedTimeLine';
export * from './constants/Client.RoutesDictionary';
export * from './constants/Client.TableHeader';
export * from './constants/Client.TabsForm';
export * from './constants/Client.TypeSelect';
export * from './models/Client';
export * from './router/Router.Client';
export * from './schemas/Client.BasicSchema';
export * from './schemas/Client.Schema';
export * from './services/Client.ApiPetitions';
