import { SelectOption } from "@models";

export const COUNTRIES: SelectOption[] = [
    { value: 'AR', label: '🇦🇷 Argentina' },
    { value: 'BO', label: '🇧🇴 Bolivia' },
    { value: 'BR', label: '🇧🇷 Brazil' },
    { value: 'CA', label: '🇨🇦 Canada' },
    { value: 'CL', label: '🇨🇱 Chile' },
    { value: 'CO', label: '🇨🇴 Colombia' },
    { value: 'CR', label: '🇨🇷 Costa Rica' },
    { value: 'CU', label: '🇨🇺 Cuba' },
    { value: 'DO', label: '🇩🇴 Dominican Republic' },
    { value: 'EC', label: '🇪🇨 Ecuador' },
    { value: 'SV', label: '🇸🇻 El Salvador' },
    { value: 'ES', label: '🇪🇸 Spain' },
    { value: 'GT', label: '🇬🇹 Guatemala' },
    { value: 'HT', label: '🇭🇹 Haiti' },
    { value: 'HN', label: '🇭🇳 Honduras' },
    { value: 'JM', label: '🇯🇲 Jamaica' },
    { value: 'MX', label: '🇲🇽 Mexico' },
    { value: 'NI', label: '🇳🇮 Nicaragua' },
    { value: 'PA', label: '🇵🇦 Panama' },
    { value: 'PY', label: '🇵🇾 Paraguay' },
    { value: 'PE', label: '🇵🇪 Peru' },
    { value: 'PR', label: '🇵🇷 Puerto Rico' },
    { value: 'UY', label: '🇺🇾 Uruguay' },
    { value: 'US', label: '🇺🇸 United States' },
    { value: 'VE', label: '🇻🇪 Venezuela' },
    { value: 'AT', label: '🇦🇹 Austria' },
    { value: 'AU', label: '🇦🇺 Australia' },
    { value: 'BE', label: '🇧🇪 Belgium' },
    { value: 'BG', label: '🇧🇬 Bulgaria' },
    { value: 'BY', label: '🇧🇾 Belarus' },
    { value: 'CN', label: '🇨🇳 China' },
    { value: 'DE', label: '🇩🇪 Germany' },
    { value: 'DK', label: '🇩🇰 Denmark' },
    { value: 'EE', label: '🇪🇪 Estonia' },
    { value: 'FI', label: '🇫🇮 Finland' },
    { value: 'FR', label: '🇫🇷 France' },
    { value: 'GB', label: '🇬🇧 United Kingdom' },
    { value: 'GR', label: '🇬🇷 Greece' },
    { value: 'HR', label: '🇭🇷 Croatia' },
    { value: 'HU', label: '🇭🇺 Hungary' },
    { value: 'ID', label: '🇮🇩 Indonesia' },
    { value: 'IE', label: '🇮🇪 Ireland' },
    { value: 'IN', label: '🇮🇳 India' },
    { value: 'IQ', label: '🇮🇶 Iraq' },
    { value: 'IS', label: '🇮🇸 Iceland' },
    { value: 'IT', label: '🇮🇹 Italy' },
    { value: 'JP', label: '🇯🇵 Japan' },
    { value: 'KE', label: '🇰🇪 Kenya' },
    { value: 'KR', label: '🇰🇷 South Korea' },
    { value: 'KW', label: '🇰🇼 Kuwait' },
    { value: 'KZ', label: '🇰🇿 Kazakhstan' },
    { value: 'LB', label: '🇱🇧 Lebanon' },
    { value: 'LK', label: '🇱🇰 Sri Lanka' },
    { value: 'LT', label: '🇱🇹 Lithuania' },
    { value: 'LU', label: '🇱🇺 Luxembourg' },
    { value: 'LV', label: '🇱🇻 Latvia' },
    { value: 'LY', label: '🇱🇾 Libya' },
    { value: 'MA', label: '🇲🇦 Morocco' },
    { value: 'MD', label: '🇲🇩 Moldova' },
    { value: 'ME', label: '🇲🇪 Montenegro' },
    { value: 'MK', label: '🇲🇰 North Macedonia' },
    { value: 'MN', label: '🇲🇳 Mongolia' },
    { value: 'MO', label: '🇲🇴 Macau' },
    { value: 'MP', label: '🇲🇵 Northern Mariana Islands' },
    { value: 'MQ', label: '🇲🇶 Martinique' },
    { value: 'MR', label: '🇲🇷 Mauritania' },
    { value: 'MU', label: '🇲🇺 Mauritius' },
    { value: 'MV', label: '🇲🇻 Maldives' },
    { value: 'MW', label: '🇲🇼 Malawi' },
    { value: 'MY', label: '🇲🇾 Malaysia' },
    { value: 'MZ', label: '🇲🇿 Mozambique' },
    { value: 'NA', label: '🇳🇦 Namibia' },
    { value: 'NE', label: '🇳🇪 Niger' },
    { value: 'NG', label: '🇳🇬 Nigeria' },
    { value: 'NL', label: '🇳🇱 Netherlands' },
    { value: 'NO', label: '🇳🇴 Norway' },
    { value: 'NP', label: '🇳🇵 Nepal' },
    { value: 'NR', label: '🇳🇷 Nauru' },
    { value: 'NZ', label: '🇳🇿 New Zealand' },
    { value: 'OM', label: '🇴🇲 Oman' },
    { value: 'PF', label: '🇵🇫 French Polynesia' },
    { value: 'PG', label: '🇵🇬 Papua New Guinea' },
    { value: 'PH', label: '🇵🇭 Philippines' },
    { value: 'PK', label: '🇵🇰 Pakistan' },
    { value: 'PL', label: '🇵🇱 Poland' },
    { value: 'PT', label: '🇵🇹 Portugal' },
    { value: 'QA', label: '🇶🇦 Qatar' },
    { value: 'RE', label: '🇷🇪 Réunion' },
    { value: 'RO', label: '🇷🇴 Romania' },
    { value: 'RS', label: '🇷🇸 Serbia' },
    { value: 'RU', label: '🇷🇺 Russia' },
    { value: 'RW', label: '🇷🇼 Rwanda' },
    { value: 'SA', label: '🇸🇦 Saudi Arabia' },
    { value: 'SB', label: '🇸🇧 Solomon Islands' },
    { value: 'SC', label: '🇸🇨 Seychelles' },
    { value: 'SD', label: '🇸🇩 Sudan' },
    { value: 'SE', label: '🇸🇪 Sweden' },
    { value: 'SG', label: '🇸🇬 Singapore' },
    { value: 'SH', label: '🇸🇭 Saint Helena' },
    { value: 'SI', label: '🇸🇮 Slovenia' },
    { value: 'SK', label: '🇸🇰 Slovakia' },
    { value: 'SL', label: '🇸🇱 Sierra Leone' },
    { value: 'SM', label: '🇸🇲 San Marino' },
    { value: 'SN', label: '🇸🇳 Senegal' },
    { value: 'SO', label: '🇸🇴 Somalia' },
    { value: 'SR', label: '🇸🇷 Suriname' },
    { value: 'SS', label: '🇸🇸 South Sudan' },
    { value: 'ST', label: '🇸🇹 São Tomé and Príncipe' },
    { value: 'SY', label: '🇸🇾 Syria' },
    { value: 'SZ', label: '🇸🇿 Eswatini' },
    { value: 'TC', label: '🇹🇨 Turks and Caicos Islands' },
    { value: 'TD', label: '🇹🇩 Chad' },
    { value: 'TF', label: '🇹🇫 French Southern Territories' },
    { value: 'TG', label: '🇹🇬 Togo' },
    { value: 'TH', label: '🇹🇭 Thailand' },
    { value: 'TJ', label: '🇹🇯 Tajikistan' },
    { value: 'TK', label: '🇹🇰 Tokelau' },
    { value: 'TL', label: '🇹🇱 Timor-Leste' },
    { value: 'TM', label: '🇹🇲 Turkmenistan' },
    { value: 'TN', label: '🇹🇳 Tunisia' },
    { value: 'TO', label: '🇹🇴 Tonga' },
    { value: 'TR', label: '🇹🇷 Turkey' },
    { value: 'TT', label: '🇹🇹 Trinidad and Tobago' },
    { value: 'TV', label: '🇹🇻 Tuvalu' },
    { value: 'TZ', label: '🇹🇿 Tanzania' },
    { value: 'UA', label: '🇺🇦 Ukraine' },
    { value: 'UG', label: '🇺🇬 Uganda' },
    { value: 'UZ', label: '🇺🇿 Uzbekistan' },
    { value: 'VA', label: '🇻🇦 Vatican City' },
    { value: 'VC', label: '🇻🇨 Saint Vincent and the Grenadines' },
    { value: 'VN', label: '🇻🇳 Vietnam' },
    { value: 'VU', label: '🇻🇺 Vanuatu' },
    { value: 'WF', label: '🇼🇫 Wallis and Futuna' },
    { value: 'WS', label: '🇼🇸 Samoa' },
    { value: 'YE', label: '🇾🇪 Yemen' },
    { value: 'ZA', label: '🇿🇦 South Africa' },
    { value: 'ZM', label: '🇿🇲 Zambia' },
    { value: 'ZW', label: '🇿🇼 Zimbabwe' },
] as const;
