export * from "./adapters/TypePrice.ApiAdapter";
export { default as Form } from "./components/Form.TypePrice.vue";
export { default as List } from "./components/List.TypePrice.vue";
export * from "./constans/TypePrice.DefaultFormValue";
export * from "./constans/TypePrice.RoutesDictionary";
export * from "./constans/TypePrice.SelectOption";
export * from "./constans/TypePrice.TableHeader";
export * from "./models/TypePrice";
export * from "./router/Router.TypePrice";
export * from "./schemas/TypePrice.Schema";
export * from "./services/TypePrice.ApiPetitions";
